### ISSUE TITLE
add support for kubernetes clouds

### ISSUE THREAD

**Issue by zxhdaze** [canonical/juju-backup-all#20]
Investigate and implement backup support for k8s clouds. Perhaps it's only using the get-kubeconfig action?

https://charmhub.io/containers-kubernetes-master/actions

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-04-04T16:38:02Z
 * owner: [thogarre](https://launchpad.net/~thogarre)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1967780)

**Comment by jneo8** [comment]
Note:

The backup control flow:

- [juju-backup-all call model.create_backup](https://github.com/canonical/juju-backup-all/blob/fdc461e7e65c36b267112558be8f0c083854eda8/jujubackupall/utils.py#L186)
- [python-lib-juju use BackupFacade](https://github.com/juju/python-libjuju/blob/ebf3c0d3cfae8797eb1c89760a44561eeaff034d/juju/model.py#L1661)
- [juju verify it's not supported by container mode;](https://github.com/juju/juju/blob/e6c41fc5333c166c6460041aaa4428a77ab321a3/cmd/modelcmd/modelcommand.go#L599)

**Comment by aieri** [comment]
This request is unclear... what should be in scope for a k8s backup?
Closing for now, feel free to reopen if still valid.
