### ISSUE TITLE
No space left on device when doing the backup.

### ISSUE THREAD

**Issue by jneo8** [canonical/juju-backup-all#49]
The backup directory is hardcoded (e.g., [see here](https://github.com/canonical/juju-backup-all/blob/5f40a84060f4e6775e8967ae89a9ea430a3ef3b0/jujubackupall/backup.py#L117)). If there is insufficient space, the backup will fail.

To resolve this, the directory should be parameterized. The next step is to add this parameter as a configuration option in the charm. We should provide separate arguments for each application.

The argument should apply to below applications:
- [ ] MySQL
- [ ] etcd
- [ ] Postgresql

**Comment by chanchiwai-ray** [comment]
@jneo8 can you provide more information why this is needed? and if this is only need to for postgres?  If the disk is full, normally the charm can't help you anymore than providing error message saying that the disk is full

**Comment by jneo8** [comment]
The case we get is the disk is full on `/home/ubuntu/`, but there are some space left on `/tmp`. It depends on how user mount the disk.

The possible improvement we can do is make it become a argument/configuration that user can choose where to store the backup files.

**Comment by chanchiwai-ray** [comment]
Yeah, that's an issue (and more or less should be fixed in the postgresql charm itself) but how about the other DBs? Are they a problem or not? We need to be more precise what are we going to fix. Since currently, they are also hardcoded
